<?PHP

function getTime() 
    { 
    $a = explode (' ',microtime()); 
    return(double) $a[0] + $a[1]; 
    } 



$scz[0] = "INR=X";
$scz[1] = "EURUSD=X";
$scz[2] = "KRW=X";
$scz[3] = "AEDUSD=X";
$scz[4] = "ISKUSD=X";
$scz[5] = "JMDUSD=X";
$scz[6] = "MDL=X";
$scz[7] = "BYR=X";
$scz[8] = "THB=X";
$scz[9] = "JMD=X";
$scz[10] = "RONUSD=X";
$scz[11] = "TOPUSD=X";
$scz[12] = "DKK=X";
$scz[13] = "ARSUSD=X";
$scz[14] = "NOK=X";
$scz[15] = "ANGUSD=X";
$scz[16] = "MUR=X";
$scz[17] = "ZMK=X";
$scz[18] = "NZDUSD=X";
$scz[19] = "DZDUSD=X";
$scz[20] = "CAD=X";
$scz[21] = "XAF=X";
$scz[22] = "AED=X";
$scz[23] = "AFNUSD=X";
$scz[24] = "ALL=X";
$scz[25] = "ALLUSD=X";
$scz[26] = "ANG=X";
$scz[27] = "ANGUSD=X";
$scz[28] = "AOAUSD=X";
$scz[29] = "ARS=X";
$scz[30] = "ARSUSD=X";
$scz[31] = "AUD=X";
$scz[32] = "AWG=X";
$scz[33] = "AWGUSD=X";
$scz[34] = "AZNUSD=X";
$scz[35] = "BAM=X";
$scz[36] = "BAMUSD=X";
$scz[37] = "BBD=X";
$scz[38] = "BBDUSD=X";
$scz[39] = "BDTUSD=X";
$scz[40] = "BGNUSD=X";
$scz[41] = "BHD=X";
$scz[42] = "BIF=X";
$scz[43] = "BMD=X";
$scz[44] = "BND=X";
$scz[45] = "BOB=X";
$scz[46] = "BRL=X";
$scz[47] = "BSD=X";
$scz[48] = "BTNUSD=X";
$scz[49] = "BYR=X";
$scz[50] = "BZD=X";
$scz[51] = "CAD=X";
$scz[52] = "CDF=X";
$scz[53] = "CHF=X";
$scz[54] = "CLFUSD=X";
$scz[55] = "CLP=X";
$scz[56] = "CNY=X";
$scz[57] = "CNYUSD=X";
$scz[58] = "COP=X";
$scz[59] = "CUPUSD=X";
$scz[60] = "CVEUSD=X";
$scz[61] = "CZK=X";
$scz[62] = "DJFUSD=X";
$scz[63] = "DKK=X";
$scz[64] = "DOP=X";
$scz[65] = "DZDUSD=X";
$scz[66] = "EGP=X";
$scz[67] = "EGPUSD=X";
$scz[68] = "ERNUSD=X";
$scz[69] = "ETB=X";
$scz[70] = "EUR=X";
$scz[71] = "FIMUSD=X";
$scz[72] = "FJD=X";
$scz[73] = "FJDUSD=X";
$scz[74] = "FKPUSD=X";
$scz[75] = "GBP=X";
$scz[76] = "GELUSD=X";
$scz[77] = "GHS=X";
$scz[78] = "GHSUSD=X";
$scz[79] = "GIPUSD=X";
$scz[80] = "GMD=X";
$scz[81] = "GMDUSD=X";
$scz[82] = "GNF=X";
$scz[83] = "GTQ=X";
$scz[84] = "GTQUSD=X";
$scz[85] = "HKD=X";
$scz[86] = "HNL=X";
$scz[87] = "HNLUSD=X";
$scz[88] = "HRK=X";
$scz[89] = "HRKUSD=X";
$scz[90] = "HTG=X";
$scz[91] = "HTGUSD=X";
$scz[92] = "HUF=X";
$scz[93] = "IDR=X";
$scz[94] = "IEP=X";
$scz[95] = "IEPUSD=X";
$scz[96] = "ILS=X";
$scz[97] = "ILSUSD=X";
$scz[98] = "INR=X";
$scz[99] = "INRUSD=X";
$scz[100] = "IQD=X";
$scz[101] = "IRR=X";
$scz[102] = "ISKUSD=X";
$scz[103] = "JMD=X";
$scz[104] = "JMDUSD=X";
$scz[105] = "JOD=X";
$scz[106] = "JODUSD=X";
$scz[107] = "JPY=X";
$scz[108] = "JPYUSD=X";
$scz[109] = "KES=X";
$scz[110] = "KESUSD=X";
$scz[111] = "KGSUSD=X";
$scz[112] = "KMF=X";
$scz[113] = "KRW=X";
$scz[114] = "KWD=X";
$scz[115] = "KWDUSD=X";
$scz[116] = "KYDUSD=X";
$scz[117] = "KZTUSD=X";
$scz[118] = "LBP=X";
$scz[119] = "LKRUSD=X";
$scz[120] = "LRDUSD=X";
$scz[121] = "LSL=X";
$scz[122] = "LSLUSD=X";
$scz[123] = "LTLUSD=X";
$scz[124] = "LVLUSD=X";
$scz[125] = "MADUSD=X";
$scz[126] = "MDL=X";
$scz[127] = "MDLUSD=X";
$scz[128] = "MKD=X";
$scz[129] = "MKDUSD=X";
$scz[130] = "MNT=X";
$scz[131] = "MOP=X";
$scz[132] = "MOPUSD=X";
$scz[133] = "MRO=X";
$scz[134] = "MUR=X";
$scz[135] = "MURUSD=X";
$scz[136] = "MVR=X";
$scz[137] = "MVRUSD=X";
$scz[138] = "MWK=X";
$scz[139] = "MXN=X";
$scz[140] = "MYR=X";
$scz[141] = "MZNUSD=X";
$scz[142] = "NAD=X";
$scz[143] = "NADUSD=X";
$scz[144] = "NGN=X";
$scz[145] = "NGNUSD=X";
$scz[146] = "NIO=X";
$scz[147] = "NIOUSD=X";
$scz[148] = "NOK=X";
$scz[149] = "NPR=X";
$scz[150] = "NPRUSD=X";
$scz[151] = "NZD=X";
$scz[152] = "NZDUSD=X";
$scz[153] = "OMRUSD=X";
$scz[154] = "PAB=X";
$scz[155] = "PABUSD=X";
$scz[156] = "PEN=X";
$scz[157] = "PENUSD=X";
$scz[158] = "PGK=X";
$scz[159] = "PGKUSD=X";
$scz[160] = "PHP=X";
$scz[161] = "PKR=X";
$scz[162] = "PKRUSD=X";
$scz[163] = "PLN=X";
$scz[164] = "PLNUSD=X";
$scz[165] = "PYG=X";
$scz[166] = "QARUSD=X";
$scz[167] = "RON=X";
$scz[168] = "RONUSD=X";
$scz[169] = "RSDUSD=X";
$scz[170] = "RUB=X";
$scz[171] = "RWF=X";
$scz[172] = "SAR=X";
$scz[173] = "SBD=X";
$scz[174] = "SCR=X";
$scz[175] = "SDGUSD=X";
$scz[176] = "SEK=X";
$scz[177] = "SGD=X";
$scz[178] = "SLL=X";
$scz[179] = "SRDUSD=X";
$scz[180] = "STD=X";
$scz[181] = "SVC=X";
$scz[182] = "SVCUSD=X";
$scz[183] = "SYPUSD=X";
$scz[184] = "SZL=X";
$scz[185] = "SZLUSD=X";
$scz[186] = "THB=X";
$scz[187] = "TJSUSD=X";
$scz[188] = "TNDUSD=X";
$scz[189] = "TOP=X";
$scz[190] = "TRY=X";
$scz[191] = "TTD=X";
$scz[192] = "TWD=X";
$scz[193] = "UAHUSD=X";
$scz[194] = "UGX=X";
$scz[195] = "UYU=X";
$scz[196] = "GCQ12.CMX";
$scz[197] = "CLQ12.NYM";
$scz[198] = "CR-Y.NYB";

$sc[0] = "USDINR";
$sc[1] = "EURUSD";
$sc[2] = "USDKRW";
$sc[3] = "AEDUSD";
$sc[4] = "ISKUSD";
$sc[5] = "JMDUSD";
$sc[6] = "USDMDL";
$sc[7] = "USDBYR";
$sc[8] = "USDTHB";
$sc[9] = "USDJMD";
$sc[10] = "RONUSD";
$sc[11] = "TOPUSD";
$sc[12] = "USDDKK";
$sc[13] = "ARSUSD";
$sc[14] = "USDNOK";
$sc[15] = "ANGUSD";
$sc[16] = "USDMUR";
$sc[17] = "USDZMK";
$sc[18] = "NZDUSD";
$sc[19] = "DZDUSD";
$sc[20] = "USDCAD";
$sc[21] = "USDXAF";
$sc[22] = "USDAED";
$sc[23] = "AFNUSD";
$sc[24] = "USDALL";
$sc[25] = "ALLUSD";
$sc[26] = "USDANG";
$sc[27] = "ANGUSD";
$sc[28] = "AOAUSD";
$sc[29] = "USDARS";
$sc[30] = "ARSUSD";
$sc[31] = "USDAUD";
$sc[32] = "USDAWG";
$sc[33] = "AWGUSD";
$sc[34] = "AZNUSD";
$sc[35] = "USDBAM";
$sc[36] = "BAMUSD";
$sc[37] = "USDBBD";
$sc[38] = "BBDUSD";
$sc[39] = "BDTUSD";
$sc[40] = "BGNUSD";
$sc[41] = "USDBHD";
$sc[42] = "USDBIF";
$sc[43] = "USDBMD";
$sc[44] = "USDBND";
$sc[45] = "USDBOB";
$sc[46] = "USDBRL";
$sc[47] = "USDBSD";
$sc[48] = "BTNUSD";
$sc[49] = "USDBYR";
$sc[50] = "USDBZD";
$sc[51] = "USDCAD";
$sc[52] = "USDCDF";
$sc[53] = "USDCHF";
$sc[54] = "CLFUSD";
$sc[55] = "USDCLP";
$sc[56] = "USDCNY";
$sc[57] = "CNYUSD";
$sc[58] = "USDCOP";
$sc[59] = "CUPUSD";
$sc[60] = "CVEUSD";
$sc[61] = "USDCZK";
$sc[62] = "DJFUSD";
$sc[63] = "USDDKK";
$sc[64] = "USDDOP";
$sc[65] = "DZDUSD";
$sc[66] = "USDEGP";
$sc[67] = "EGPUSD";
$sc[68] = "ERNUSD";
$sc[69] = "USDETB";
$sc[70] = "USDEUR";
$sc[71] = "FIMUSD";
$sc[72] = "USDFJD";
$sc[73] = "FJDUSD";
$sc[74] = "FKPUSD";
$sc[75] = "USDGBP";
$sc[76] = "GELUSD";
$sc[77] = "USDGHS";
$sc[78] = "GHSUSD";
$sc[79] = "GIPUSD";
$sc[80] = "USDGMD";
$sc[81] = "GMDUSD";
$sc[82] = "USDGNF";
$sc[83] = "USDGTQ";
$sc[84] = "GTQUSD";
$sc[85] = "USDHKD";
$sc[86] = "USDHNL";
$sc[87] = "HNLUSD";
$sc[88] = "USDHRK";
$sc[89] = "HRKUSD";
$sc[90] = "USDHTG";
$sc[91] = "HTGUSD";
$sc[92] = "USDHUF";
$sc[93] = "USDIDR";
$sc[94] = "USDIEP";
$sc[95] = "IEPUSD";
$sc[96] = "USDILS";
$sc[97] = "ILSUSD";
$sc[98] = "USDINR";
$sc[99] = "INRUSD";
$sc[100] = "USDIQD";
$sc[101] = "USDIRR";
$sc[102] = "ISKUSD";
$sc[103] = "USDJMD";
$sc[104] = "JMDUSD";
$sc[105] = "USDJOD";
$sc[106] = "JODUSD";
$sc[107] = "USDJPY";
$sc[108] = "JPYUSD";
$sc[109] = "USDKES";
$sc[110] = "KESUSD";
$sc[111] = "KGSUSD";
$sc[112] = "USDKMF";
$sc[113] = "USDKRW";
$sc[114] = "USDKWD";
$sc[115] = "KWDUSD";
$sc[116] = "KYDUSD";
$sc[117] = "KZTUSD";
$sc[118] = "USDLBP";
$sc[119] = "LKRUSD";
$sc[120] = "LRDUSD";
$sc[121] = "USDLSL";
$sc[122] = "LSLUSD";
$sc[123] = "LTLUSD";
$sc[124] = "LVLUSD";
$sc[125] = "MADUSD";
$sc[126] = "USDMDL";
$sc[127] = "MDLUSD";
$sc[128] = "USDMKD";
$sc[129] = "MKDUSD";
$sc[130] = "USDMNT";
$sc[131] = "USDMOP";
$sc[132] = "MOPUSD";
$sc[133] = "USDMRO";
$sc[134] = "USDMUR";
$sc[135] = "MURUSD";
$sc[136] = "USDMVR";
$sc[137] = "MVRUSD";
$sc[138] = "USDMWK";
$sc[139] = "USDMXN";
$sc[140] = "USDMYR";
$sc[141] = "MZNUSD";
$sc[142] = "USDNAD";
$sc[143] = "NADUSD";
$sc[144] = "USDNGN";
$sc[145] = "NGNUSD";
$sc[146] = "USDNIO";
$sc[147] = "NIOUSD";
$sc[148] = "USDNOK";
$sc[149] = "USDNPR";
$sc[150] = "NPRUSD";
$sc[151] = "USDNZD";
$sc[152] = "NZDUSD";
$sc[153] = "OMRUSD";
$sc[154] = "USDPAB";
$sc[155] = "PABUSD";
$sc[156] = "USDPEN";
$sc[157] = "PENUSD";
$sc[158] = "USDPGK";
$sc[159] = "PGKUSD";
$sc[160] = "USDPHP";
$sc[161] = "USDPKR";
$sc[162] = "PKRUSD";
$sc[163] = "USDPLN";
$sc[164] = "PLNUSD";
$sc[165] = "USDPYG";
$sc[166] = "QARUSD";
$sc[167] = "USDRON";
$sc[168] = "RONUSD";
$sc[169] = "RSDUSD";
$sc[170] = "USDRUB";
$sc[171] = "USDRWF";
$sc[172] = "USDSAR";
$sc[173] = "USDSBD";
$sc[174] = "USDSCR";
$sc[175] = "SDGUSD";
$sc[176] = "USDSEK";
$sc[177] = "USDSGD";
$sc[178] = "USDSLL";
$sc[179] = "SRDUSD";
$sc[180] = "USDSTD";
$sc[181] = "USDSVC";
$sc[182] = "SVCUSD";
$sc[183] = "SYPUSD";
$sc[184] = "USDSZL";
$sc[185] = "SZLUSD";
$sc[186] = "USDTHB";
$sc[187] = "TJSUSD";
$sc[188] = "TNDUSD";
$sc[189] = "USDTOP";
$sc[190] = "USDTRY";
$sc[191] = "USDTTD";
$sc[192] = "USDTWD";
$sc[193] = "UAHUSD";
$sc[194] = "USDUGX";
$sc[195] = "USDUYU";
$sc[196] = "GOLD";
$sc[197] = "CRUDE";
$sc[198] = "CRBINDEX";

$mk = 0;
$url[0] = "http://finance.yahoo.com/d/quotes.csv?e=.csv&f=sl1d1t1&s=ILSUSD=X+INR=X+INRUSD=X+IQD=X+IRR=X+ISKUSD=X+JMD=X+JMDUSD=X+JOD=X+JODUSD=X+JPY=X+JPYUSD=X+KES=X+KESUSD=X+KGSUSD=X+KMF=X+KRW=X+KWD=X+KWDUSD=X+KYDUSD=X+KZTUSD=X+LBP=X+LKRUSD=X+LRDUSD=X+LSL=X+LSLUSD=X+LTLUSD=X+LVLUSD=X+MADUSD=X+MDL=X+MDLUSD=X+MKD=X+MKDUSD=X+MNT=X+MOP=X+MOPUSD=X+MRO=X+MUR=X+MURUSD=X+MVR=X+MVRUSD=X+MWK=X+MXN=X+MYR=X+MZNUSD=X+NAD=X+NADUSD=X+NGN=X+NGNUSD=X+NIO=X+NIOUSD=X+NOK=X+NPR=X+NPRUSD=X+NZD=X+NZDUSD=X+OMRUSD=X+PAB=X+PABUSD=X+PEN=X+PENUSD=X+PGK=X+PGKUSD=X+PHP=X+PKR=X+PKRUSD=X+PLN=X+PLNUSD=X+PYG=X+QARUSD=X+RON=X+RONUSD=X+RSDUSD=X+RUB=X+RWF=X+SAR=X+SBD=X+SCR=X+SDGUSD=X+SEK=X+SGD=X+SLL=X+SRDUSD=X+STD=X+SVC=X+SVCUSD=X+SYPUSD=X+SZL=X+SZLUSD=X+THB=X+TJSUSD=X+TNDUSD=X+TOP=X+TRY=X+TTD=X+TWD=X+UAHUSD=X+UGX=X+UYU=X+GCQ12.CMX+CLQ12.NYM+CR-Y.NYB&ex=.csv";
$url[1] = "http://finance.yahoo.com/d/quotes.csv?e=.csv&f=sl1d1t1&s=INR=X+EURUSD=X+KRW=X+AEDUSD=X+ISKUSD=X+JMDUSD=X+MDL=X+BYR=X+THB=X+JMD=X+RONUSD=X+TOPUSD=X+DKK=X+ARSUSD=X+NOK=X+ANGUSD=X+MUR=X+ZMK=X+NZDUSD=X+DZDUSD=X+CAD=X+XAF=X+AED=X+AFNUSD=X+ALL=X+ALLUSD=X+ANG=X+ANGUSD=X+AOAUSD=X+ARS=X+ARSUSD=X+AUD=X+AWG=X+AWGUSD=X+AZNUSD=X+BAM=X+BAMUSD=X+BBD=X+BBDUSD=X+BDTUSD=X+BGNUSD=X+BHD=X+BIF=X+BMD=X+BND=X+BOB=X+BRL=X+BSD=X+BTNUSD=X+BYR=X+BZD=X+CAD=X+CDF=X+CHF=X+CLFUSD=X+CLP=X+CNY=X+CNYUSD=X+COP=X+CUPUSD=X+CVEUSD=X+CZK=X+DJFUSD=X+DKK=X+DOP=X+DZDUSD=X+EGP=X+EGPUSD=X+ERNUSD=X+ETB=X+EUR=X+EURUSD=X+EURUSDCB.ME+FIMUSD=X+FJD=X+FJDUSD=X+FKPUSD=X+GBP=X+GELUSD=X+GHS=X+GHSUSD=X+GIPUSD=X+GMD=X+GMDUSD=X+GNF=X+GTQ=X+GTQUSD=X+HKD=X+HNL=X+HNLUSD=X+HRK=X+HRKUSD=X+HTG=X+HTGUSD=X+HUF=X+IDR=X+IEP=X+IEPUSD=X+ILS=X&ex=.csv";
$x = 1;



if ( $mk % 2  == 0 ) {$vc = 0; };
if ( $mk % 2 != 0 ) {$vc = 1; };
unlink("TEMP.csv");
copy ( $url[$vc], "TEMP.csv" );



for ( $i = 0; $i <= 198; $i ++ ) {
$fille = fopen("TEMP.csv", "r");

$row = 0;
while (($data = fgetcsv($fille, 80000, ",")) !== FALSE) {

if ( $data[0] == $scz[$i]) 
{ // echo $data[0].$data[1];
$datafile = $sc[$i]."LAST.txt";
$file = fopen($datafile, "w" );
fwrite( $file, $data[1] ); 
fclose( $file );


 
}
   
    $row++; 
}
fclose($fille);
$ur = "http://localhost/charity/hu/forex/".$sc[$i].".php";
$t = file_get_contents($ur);
$t = "";
}





?>