<?php

$url[0] = "http://finance.yahoo.com/d/quotes.csv?e=.csv&f=sl1d1t1&s=ILSUSD=X+INR=X+INRUSD=X+IQD=X+IRR=X+ISKUSD=X+JMD=X+JMDUSD=X+JOD=X+JODUSD=X+JPY=X+JPYUSD=X+KES=X+KESUSD=X+KGSUSD=X+KMF=X+KRW=X+KWD=X+KWDUSD=X+KYDUSD=X+KZTUSD=X+LBP=X+LKRUSD=X+LRDUSD=X+LSL=X+LSLUSD=X+LTLUSD=X+LVLUSD=X+MADUSD=X+MDL=X+MDLUSD=X+MKD=X+MKDUSD=X+MNT=X+MOP=X+MOPUSD=X+MRO=X+MUR=X+MURUSD=X+MVR=X+MVRUSD=X+MWK=X+MXN=X+MYR=X+MZNUSD=X+NAD=X+NADUSD=X+NGN=X+NGNUSD=X+NIO=X+NIOUSD=X+NOK=X+NPR=X+NPRUSD=X+NZD=X+NZDUSD=X+OMRUSD=X+PAB=X+PABUSD=X+PEN=X+PENUSD=X+PGK=X+PGKUSD=X+PHP=X+PKR=X+PKRUSD=X+PLN=X+PLNUSD=X+PYG=X+QARUSD=X+RON=X+RONUSD=X+RSDUSD=X+RUB=X+RWF=X+SAR=X+SBD=X+SCR=X+SDGUSD=X+SEK=X+SGD=X+SLL=X+SRDUSD=X+STD=X+SVC=X+SVCUSD=X+SYPUSD=X+SZL=X+SZLUSD=X+THB=X+TJSUSD=X+TNDUSD=X+TOP=X+TRY=X+TTD=X+TWD=X+UAHUSD=X+UGX=X+UYU=X+GCM12.CMX+CLN12.NYM&ex=.csv";
$url[1] = "http://finance.yahoo.com/d/quotes.csv?e=.csv&f=sl1d1t1&s=INR=X+EURUSD=X+KRW=X+AEDUSD=X+ISKUSD=X+JMDUSD=X+MDL=X+BYR=X+THB=X+JMD=X+RONUSD=X+TOPUSD=X+DKK=X+ARSUSD=X+NOK=X+ANGUSD=X+MUR=X+ZMK=X+NZDUSD=X+DZDUSD=X+CAD=X+XAF=X+AED=X+AFNUSD=X+ALL=X+ALLUSD=X+ANG=X+ANGUSD=X+AOAUSD=X+ARS=X+ARSUSD=X+AUD=X+AWG=X+AWGUSD=X+AZNUSD=X+BAM=X+BAMUSD=X+BBD=X+BBDUSD=X+BDTUSD=X+BGNUSD=X+BHD=X+BIF=X+BMD=X+BND=X+BOB=X+BRL=X+BSD=X+BTNUSD=X+BYR=X+BZD=X+CAD=X+CDF=X+CHF=X+CLFUSD=X+CLP=X+CNY=X+CNYUSD=X+COP=X+CUPUSD=X+CVEUSD=X+CZK=X+DJFUSD=X+DKK=X+DOP=X+DZDUSD=X+EGP=X+EGPUSD=X+ERNUSD=X+ETB=X+EUR=X+EURUSD=X+EURUSDCB.ME+FIMUSD=X+FJD=X+FJDUSD=X+FKPUSD=X+GBP=X+GELUSD=X+GHS=X+GHSUSD=X+GIPUSD=X+GMD=X+GMDUSD=X+GNF=X+GTQ=X+GTQUSD=X+HKD=X+HNL=X+HNLUSD=X+HRK=X+HRKUSD=X+HTG=X+HTGUSD=X+HUF=X+IDR=X+IEP=X+IEPUSD=X+ILS=X&ex=.csv";
$u = file_get_contents($url[0]);

echo $u;

$u = file_get_contents($url[1]);

echo $u;

?>